pipeline {
    agent any

    environment {
        GITHUB_TOKEN = credentials('github-token') // Utilise l'ID des identifiants
    }

    stages {
        stage('Checkout') {
            steps {
                // Cloner le dépôt en utilisant le token GitHub
                git branch: 'main', url: "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/tasnimkh24/Ml_Project.git"
            }
        }

        stage('Install Dependencies') {
            steps {
                // Créer et activer un environnement virtuel
                sh 'python3 -m venv venv'
                sh 'source venv/bin/activate && pip install -r requirements.txt'
            }
        }

        stage('Prepare Data') {
            steps {
                // Exécuter le script de préparation des données
                sh 'source venv/bin/activate && python3 src/main.py --train data/train.csv --test data/test.csv --prepare'
            }
        }

        stage('Train Model') {
            steps {
                // Exécuter le script d'entraînement du modèle
                sh 'source venv/bin/activate && python3 src/main.py --train data/train.csv --test data/test.csv --train'
            }
        }

        stage('Evaluate Model') {
            steps {
                // Exécuter le script d'évaluation du modèle
                sh 'source venv/bin/activate && python3 src/main.py --test data/test.csv --evaluate'
            }
        }

        stage('Deploy Model') {
            steps {
                // Exécuter le script de déploiement du modèle
                sh 'source venv/bin/activate && python3 src/main.py --deploy'
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed!'
        }
        success {
            echo 'Pipeline succeeded!'
        }
    }
}
